# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-28 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginNregistration_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='registration',
            name='birthday',
            field=models.DateTimeField(null='True', verbose_name='%mm-%dd-%yyyy'),
        ),
    ]
