# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-29 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginNregistration_app', '0002_auto_20190728_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='confirm_pw',
        ),
    ]
